config/routes.rb
Rails.application.routes.draw do

  resources :users, only: %i(index new create show) do
    member do
      post :comment
      get :cheers
    end
  end

  resources :goals do
    member do
      post :toggle_complete
      post :comment
      post :cheers
    end
  end
  
  resource :session, only: %i(new create destroy)

  root to: 'users#index'
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  details    :text
#  user_id    :integer          not null
#  private    :boolean          default(FALSE)
#  complete   :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Goal < ApplicationRecord
  include Commentable
  validates :title, :user_id, presence: true
  validates :title, length: { minimum: 6 }

  belongs_to :user, inverse_of: :goals
  has_many :cheers, dependent: :destroy

  def cheer_score
    cheers.count
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :logged_in?
  before_action :current_users_private_goal?, only: %i(show comment cheers)
  before_action :not_current_users_goal?, only: %i(edit update destroy toggle_complete)
  before_action :is_current_users_goal?, only: %i(cheers)
  before_action :set_goal, only: %i(show edit update destroy toggle_complete comment cheers)

  def index
    @goals = current_user.goals
    render :index
  end

  def show
    render :show
  end

  def new
    @goal = Goal.new
    render :new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id

    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    render :edit
  end

  def update
    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    @goal.destroy
    flash[:notices] = ["goal has been delete"]
    redirect_to user_url(current_user)
  end

  def toggle_complete
    @goal.toggle(:complete)
    @goal.save
    redirect_back(fallback_location: root_path)
  end

  def comment
    @comment = Comment.new(
      commentable_type: 'Goal', 
      commentable_id: params[:id], 
      comment: params[:comment], 
      author_id: current_user.id
      )
    if @comment.save
      flash[:notices] = ["Comment saved!"]
      redirect_to goal_url(@goal)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to goal_url(@goal)
    end
  end
  

  def cheers
    @cheer = Cheer.new(
      goal_id: params[:id], 
      user_id: current_user.id
      )
    if @cheer.save
      flash[:notices] = ["You cheered #{@goal.user.email} goal!"]
      redirect_to user_url(@goal.user_id)
    else
      flash[:errors] = @cheer.errors.full_messages
      redirect_to user_url(@goal.user_id)
    end
  end

  private

  def goal_params
    params.require(:goal).permit(:title, :details, :private, :complete)
  end

  def set_goal
    @goal ||= Goal.includes(:comments).find_by(id: params[:id])
  end

  def current_users_private_goal?
    if current_goal.private && current_goal.user_id != current_user.id
      flash[:notices] = ["Sorry that goal is private"]
      redirect_to user_url(current_user)
      return
    end
  end

  def is_current_users_goal?
    if current_goal.user_id == current_user.id
      flash[:errors] = ["You can't cheers your own goal"]
      redirect_to user_url(current_user)
      return
    end
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<% action_url = goal.persisted? ? goal_url(goal) : goals_url %>
<% submit_text = goal.persisted? ? "Update Goal" : "Add Goal" %>
<form action="<%= action_url %>" method="post">
  <%= auth_token %>
  <% if goal.persisted? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label>
    Title:
    <input type="text" name="goal[title]" value="<%= goal.title %>" />
  </label>

  <br>

  <label>
    Details:
    <textarea 
      name="goal[details]"><%= goal.details %></textarea>
  </label>

  <br>

  <label>
    Private?
    <input 
      type="checkbox" 
      name="goal[private]" 
      <% checked = goal.private ? "checked" : "" %> <%= checked %>>
  </label>

  <br>

  <label>
    Completed?
    <input 
      type="checkbox" 
      name="goal[complete]" 
      <% checked = goal.complete ? "checked" : "" %> <%= checked %>>
  </label>

  <br>
  
  <button type="submit"><%= submit_text %></button>
</form>

app/views/goals/_goal.html.erb
<li><a href="<%= goal_url(goal) %>"><%= goal.title %></a></li>
<p><%= goal.private ? "private" : "public" %></p>
<p><%= goal.complete ? "Complete" : "Ongoing" %></p>
<br>
<p><%= goal.details %></p>
<% if goal.user == current_user %>
  <%= completion_buttons(goal) %>
  <%= button_to("delete #{goal.title} goal", goal_url(goal), method: :delete) %>
<% elsif goal.cheers.where(user_id: current_user.id).empty? && current_user.cheers_left > 0 %>
  <%= button_to "Cheer!", cheers_goal_url(goal) %>
<% end %>

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<%= render 'form', goal: @goal %>

app/views/goals/index.html.erb
<h1>Your Goals</h1>
<ul>
  <%= render @goals %>
</ul>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form', goal: @goal %>

app/views/goals/show.html.erb
<h1>Goal:</h1>
<table>
  <tr>
    <td>Title:</td>
    <td><%= @goal.title %></td>
  </tr>
  <tr>
    <td>Details:</td>
    <td><%= @goal.details %></td>
  </tr>
  <tr>
    <td>Visibility:</td>
    <td><%= @goal.private ? "private" : "public" %></td>
  </tr>
  <tr>
    <td>Finished?:</td>
    <td><%= @goal.complete ? "Complete" : "Ongoing" %></td>
  </tr>
  <% if @goal.user == current_user %>
    <tr>
      <td>Completed?</td>
      <td><%= completion_buttons(@goal) %></td>
    </tr>
  <% end %>
</table>

<br>

<h4>Comments</h4>
<%= render 'shared/comments', user: nil, goal: @goal, comments: @goal.comments %>